export type Name = {
  n: number; slug: string; ar: string; tr: string; en: string; root: string; meaning: string; line: string;
};

// Traditional (Tirmidhi) order. Reflections are short by design — one line to sit with.
export const NAMES: Name[] = [
 {n:1,slug:"ar-rahman",ar:"ٱلرَّحْمَـٰنُ",tr:"Ar-Rahman",en:"The Most Gracious",root:"ر-ح-م",meaning:"Mercy so vast it reaches everything that exists, believer and denier alike, before anyone asks.",line:"You were shown mercy before you knew the word."},
 {n:2,slug:"ar-rahim",ar:"ٱلرَّحِيمُ",tr:"Ar-Rahim",en:"The Most Merciful",root:"ر-ح-م",meaning:"Mercy that is particular, intimate and ongoing — the mercy kept for those who turn toward Him.",line:"His mercy is not a moment. It's a habit."},
 {n:3,slug:"al-malik",ar:"ٱلْمَلِكُ",tr:"Al-Malik",en:"The King",root:"م-ل-ك",meaning:"The absolute Sovereign, whose dominion needs no army and no succession.",line:"Whatever you're gripping, He already owns."},
 {n:4,slug:"al-quddus",ar:"ٱلْقُدُّوسُ",tr:"Al-Quddus",en:"The Most Holy",root:"ق-د-س",meaning:"Utterly pure, far above every flaw, every limit and every image the mind can make.",line:"Nothing you've imagined about Him is big enough."},
 {n:5,slug:"as-salam",ar:"ٱلسَّلَامُ",tr:"As-Salam",en:"The Source of Peace",root:"س-ل-م",meaning:"Peace itself, and the One from whom all safety and wholeness flow.",line:"Peace isn't found. It's given."},
 {n:6,slug:"al-mumin",ar:"ٱلْمُؤْمِنُ",tr:"Al-Mu'min",en:"The Giver of Security",root:"أ-م-ن",meaning:"The One who grants faith and safety, and who is true to every promise He makes.",line:"He has never once broken a promise to you."},
 {n:7,slug:"al-muhaymin",ar:"ٱلْمُهَيْمِنُ",tr:"Al-Muhaymin",en:"The Guardian",root:"ه-م-ن",meaning:"The Watcher over all things, protecting and overseeing every detail of creation.",line:"You are being watched over, not watched."},
 {n:8,slug:"al-aziz",ar:"ٱلْعَزِيزُ",tr:"Al-Aziz",en:"The Almighty",root:"ع-ز-ز",meaning:"Unconquerable might and honour; nothing can overcome Him or diminish Him.",line:"Your dignity comes from His, not from them."},
 {n:9,slug:"al-jabbar",ar:"ٱلْجَبَّارُ",tr:"Al-Jabbar",en:"The Restorer",root:"ج-ب-ر",meaning:"The Compeller whose will is irresistible — and the One who mends what is broken.",line:"The same hand that can break anything is the one that mends you."},
 {n:10,slug:"al-mutakabbir",ar:"ٱلْمُتَكَبِّرُ",tr:"Al-Mutakabbir",en:"The Supreme",root:"ك-ب-ر",meaning:"Greatness that belongs to Him alone; the only One for whom pride is truth, not flaw.",line:"Pride fits Him. It never fit you."},
 {n:11,slug:"al-khaliq",ar:"ٱلْخَالِقُ",tr:"Al-Khaliq",en:"The Creator",root:"خ-ل-ق",meaning:"The One who brings into being from nothing, planning and measuring every creation.",line:"You were an idea of His before you were anything."},
 {n:12,slug:"al-bari",ar:"ٱلْبَارِئُ",tr:"Al-Bari'",en:"The Maker",root:"ب-ر-أ",meaning:"The Evolver who shapes creation into distinct, living things, each free of defect in its purpose.",line:"Nothing about you is a manufacturing error."},
 {n:13,slug:"al-musawwir",ar:"ٱلْمُصَوِّرُ",tr:"Al-Musawwir",en:"The Fashioner",root:"ص-و-ر",meaning:"The Shaper of forms, who gives every creature its unique face and figure.",line:"Your face was designed. On purpose."},
 {n:14,slug:"al-ghaffar",ar:"ٱلْغَفَّارُ",tr:"Al-Ghaffar",en:"The Ever-Forgiving",root:"غ-ف-ر",meaning:"The One who forgives again and again, covering sins so completely they are as if they never were.",line:"He forgave the last one. He'll forgive this one."},
 {n:15,slug:"al-qahhar",ar:"ٱلْقَهَّارُ",tr:"Al-Qahhar",en:"The Subduer",root:"ق-ه-ر",meaning:"The Dominant One, before whom every force and every tyrant is ultimately powerless.",line:"Whatever is crushing you is itself held down by Him."},
 {n:16,slug:"al-wahhab",ar:"ٱلْوَهَّابُ",tr:"Al-Wahhab",en:"The Bestower",root:"و-ه-ب",meaning:"The Giver of gifts freely, constantly, without expectation of return.",line:"He gives without keeping score."},
 {n:17,slug:"ar-razzaq",ar:"ٱلرَّزَّاقُ",tr:"Ar-Razzaq",en:"The Provider",root:"ر-ز-ق",meaning:"The Sustainer who provides every creature with what it needs, seen and unseen.",line:"What's yours is already on its way."},
 {n:18,slug:"al-fattah",ar:"ٱلْفَتَّاحُ",tr:"Al-Fattah",en:"The Opener",root:"ف-ت-ح",meaning:"The One who opens closed doors, hearts and matters, and judges between people with truth.",line:"Closed doors are His specialty."},
 {n:19,slug:"al-alim",ar:"ٱلْعَلِيمُ",tr:"Al-'Alim",en:"The All-Knowing",root:"ع-ل-م",meaning:"Knowledge that is total: the past, the hidden, the unspoken, and what has not yet happened.",line:"He knows the version of it you didn't say."},
 {n:20,slug:"al-qabid",ar:"ٱلْقَابِضُ",tr:"Al-Qabid",en:"The Withholder",root:"ق-ب-ض",meaning:"The One who constricts and withholds — provision, hearts, souls — by wisdom, never by accident.",line:"The tightness you feel has a reason and a limit."},
 {n:21,slug:"al-basit",ar:"ٱلْبَاسِطُ",tr:"Al-Basit",en:"The Expander",root:"ب-س-ط",meaning:"The One who opens up and expands — wealth, chests, mercy — as He wills.",line:"Room will be made. It always is."},
 {n:22,slug:"al-khafid",ar:"ٱلْخَافِضُ",tr:"Al-Khafid",en:"The Abaser",root:"خ-ف-ض",meaning:"The One who brings low the arrogant and lowers whom He wills.",line:"What goes up without Him comes down."},
 {n:23,slug:"ar-rafi",ar:"ٱلرَّافِعُ",tr:"Ar-Rafi'",en:"The Exalter",root:"ر-ف-ع",meaning:"The One who raises in rank, honour and nearness whom He wills.",line:"Your rise doesn't need their permission."},
 {n:24,slug:"al-muizz",ar:"ٱلْمُعِزُّ",tr:"Al-Mu'izz",en:"The Giver of Honour",root:"ع-ز-ز",meaning:"The One who grants honour and strength to whom He chooses.",line:"Honour is given, not taken."},
 {n:25,slug:"al-mudhill",ar:"ٱلْمُذِلُّ",tr:"Al-Mudhill",en:"The Giver of Dishonour",root:"ذ-ل-ل",meaning:"The One who humbles and disgraces whom He wills, with perfect justice.",line:"Humiliation is only ever from one direction."},
 {n:26,slug:"as-sami",ar:"ٱلسَّمِيعُ",tr:"As-Sami'",en:"The All-Hearing",root:"س-م-ع",meaning:"Hearing that misses nothing: every whisper, every silent plea, in every language at once.",line:"You've never once spoken to no one."},
 {n:27,slug:"al-basir",ar:"ٱلْبَصِيرُ",tr:"Al-Basir",en:"The All-Seeing",root:"ب-ص-ر",meaning:"Sight that reaches everything, the outward and the inward, the done and the intended.",line:"He saw the effort nobody else noticed."},
 {n:28,slug:"al-hakam",ar:"ٱلْحَكَمُ",tr:"Al-Hakam",en:"The Judge",root:"ح-ك-م",meaning:"The Arbiter whose judgement is final and flawless, and never unfair.",line:"The last word isn't theirs."},
 {n:29,slug:"al-adl",ar:"ٱلْعَدْلُ",tr:"Al-'Adl",en:"The Utterly Just",root:"ع-د-ل",meaning:"Justice itself, in whom there is no trace of wrong, and who places everything where it belongs.",line:"Nothing unjust will be left uncorrected."},
 {n:30,slug:"al-latif",ar:"ٱللَّطِيفُ",tr:"Al-Latif",en:"The Subtle, The Kind",root:"ل-ط-ف",meaning:"Gentle beyond perception, working kindness into your life in ways you only notice later.",line:"Some of His kindness you'll only recognise in hindsight."},
 {n:31,slug:"al-khabir",ar:"ٱلْخَبِيرُ",tr:"Al-Khabir",en:"The All-Aware",root:"خ-ب-ر",meaning:"Aware of the inner reality of all things — the hidden, the minute, the true motive.",line:"He knows why you really did it. And still loves you."},
 {n:32,slug:"al-halim",ar:"ٱلْحَلِيمُ",tr:"Al-Halim",en:"The Forbearing",root:"ح-ل-م",meaning:"Patient and gentle with wrongdoing, delaying punishment to give room for return.",line:"He's not in a hurry to punish you. Stop punishing yourself."},
 {n:33,slug:"al-azim",ar:"ٱلْعَظِيمُ",tr:"Al-'Azim",en:"The Magnificent",root:"ع-ظ-م",meaning:"Greatness beyond measure, beyond comparison, beyond the reach of language.",line:"Your problem is big. He is bigger."},
 {n:34,slug:"al-ghafur",ar:"ٱلْغَفُورُ",tr:"Al-Ghafur",en:"The Much-Forgiving",root:"غ-ف-ر",meaning:"The One whose forgiveness is vast enough to cover the greatest sins.",line:"There is no sin that outsizes His forgiveness."},
 {n:35,slug:"ash-shakur",ar:"ٱلشَّكُورُ",tr:"Ash-Shakur",en:"The Appreciative",root:"ش-ك-ر",meaning:"The One who rewards small deeds immensely and appreciates every effort made for Him.",line:"He noticed. He remembers. He'll multiply it."},
 {n:36,slug:"al-ali",ar:"ٱلْعَلِيُّ",tr:"Al-'Ali",en:"The Most High",root:"ع-ل-و",meaning:"Exalted above all of creation in essence, rank and power.",line:"Look up. Not around."},
 {n:37,slug:"al-kabir",ar:"ٱلْكَبِيرُ",tr:"Al-Kabir",en:"The Most Great",root:"ك-ب-ر",meaning:"Greater than anything — which is exactly why they say Allahu Akbar.",line:"Say it once and mean it: He is greater."},
 {n:38,slug:"al-hafiz",ar:"ٱلْحَفِيظُ",tr:"Al-Hafiz",en:"The Preserver",root:"ح-ف-ظ",meaning:"The Protector who guards all things from loss and preserves His servants from harm.",line:"Everything that's kept safe is kept safe by Him."},
 {n:39,slug:"al-muqit",ar:"ٱلْمُقِيتُ",tr:"Al-Muqit",en:"The Sustainer",root:"ق-و-ت",meaning:"The Nourisher who gives every creature its portion of strength and sustenance.",line:"You'll have enough for today. That was the deal."},
 {n:40,slug:"al-hasib",ar:"ٱلْحَسِيبُ",tr:"Al-Hasib",en:"The Reckoner",root:"ح-س-ب",meaning:"The One who takes account of all things, and the One who is sufficient for you.",line:"Hasbunallah — He is enough. Say it when nothing else is."},
 {n:41,slug:"al-jalil",ar:"ٱلْجَلِيلُ",tr:"Al-Jalil",en:"The Majestic",root:"ج-ل-ل",meaning:"Sublime majesty and grandeur in every attribute, beyond every description.",line:"Majesty is His default setting."},
 {n:42,slug:"al-karim",ar:"ٱلْكَرِيمُ",tr:"Al-Karim",en:"The Most Generous",root:"ك-ر-م",meaning:"Generosity that gives before asking, beyond deserving, and more than was hoped.",line:"Ask Him for more than you think you deserve. That's the point."},
 {n:43,slug:"ar-raqib",ar:"ٱلرَّقِيبُ",tr:"Ar-Raqib",en:"The Watchful",root:"ر-ق-ب",meaning:"Ever-observant, never distracted, never asleep — attending to every creature always.",line:"He doesn't look away, even when you wish He would."},
 {n:44,slug:"al-mujib",ar:"ٱلْمُجِيبُ",tr:"Al-Mujib",en:"The Responsive",root:"ج-و-ب",meaning:"The One who answers every call, in the form and at the time that is best.",line:"Every dua has been answered. Not every answer was yes, yet."},
 {n:45,slug:"al-wasi",ar:"ٱلْوَاسِعُ",tr:"Al-Wasi'",en:"The All-Encompassing",root:"و-س-ع",meaning:"Boundless in mercy, knowledge and provision; nothing is outside His reach.",line:"There's no edge to Him for you to fall off."},
 {n:46,slug:"al-hakim",ar:"ٱلْحَكِيمُ",tr:"Al-Hakim",en:"The All-Wise",root:"ح-ك-م",meaning:"Perfect wisdom in every decree, even the ones that don't make sense yet.",line:"He allows hardship for reasons you'll understand later."},
 {n:47,slug:"al-wadud",ar:"ٱلْوَدُودُ",tr:"Al-Wadud",en:"The Most Loving",root:"و-د-د",meaning:"Love that is active and affectionate — He loves His servants and makes them beloved.",line:"He loves you in the mess, not after it."},
 {n:48,slug:"al-majid",ar:"ٱلْمَجِيدُ",tr:"Al-Majid",en:"The Most Glorious",root:"م-ج-د",meaning:"Glory, honour and nobility that are infinite and His alone.",line:"Glory that doesn't need an audience."},
 {n:49,slug:"al-baith",ar:"ٱلْبَاعِثُ",tr:"Al-Ba'ith",en:"The Resurrector",root:"ب-ع-ث",meaning:"The One who raises the dead, sends the messengers, and brings hearts back to life.",line:"If He can raise the dead, He can revive your heart."},
 {n:50,slug:"ash-shahid",ar:"ٱلشَّهِيدُ",tr:"Ash-Shahid",en:"The Witness",root:"ش-ه-د",meaning:"Present to all things, witnessing everything as it truly happened.",line:"He saw what happened to you. It counted."},
 {n:51,slug:"al-haqq",ar:"ٱلْحَقُّ",tr:"Al-Haqq",en:"The Truth",root:"ح-ق-ق",meaning:"The absolutely Real, whose existence and word are the only certainties.",line:"Everything else is a maybe. He is the yes."},
 {n:52,slug:"al-wakil",ar:"ٱلْوَكِيلُ",tr:"Al-Wakil",en:"The Trustee",root:"و-ك-ل",meaning:"The One you can hand your affairs to completely, who manages them better than you could.",line:"Hand it over. He's better at this than you."},
 {n:53,slug:"al-qawiyy",ar:"ٱلْقَوِيُّ",tr:"Al-Qawiyy",en:"The All-Strong",root:"ق-و-ي",meaning:"Strength that never tires, never weakens and never needs help.",line:"Borrow your strength from the One who never runs out."},
 {n:54,slug:"al-matin",ar:"ٱلْمَتِينُ",tr:"Al-Matin",en:"The Firm",root:"م-ت-ن",meaning:"Unshakeable, steadfast; His power is firm and His promise is solid.",line:"Stand on Him. He doesn't move."},
 {n:55,slug:"al-waliyy",ar:"ٱلْوَلِيُّ",tr:"Al-Waliyy",en:"The Protecting Friend",root:"و-ل-ي",meaning:"The Ally and Guardian who stands closest to those who believe.",line:"You have a friend in high places. The highest."},
 {n:56,slug:"al-hamid",ar:"ٱلْحَمِيدُ",tr:"Al-Hamid",en:"The Praiseworthy",root:"ح-م-د",meaning:"Deserving of all praise in every state, whether praised or not.",line:"Alhamdulillah isn't a reaction. It's a fact."},
 {n:57,slug:"al-muhsi",ar:"ٱلْمُحْصِي",tr:"Al-Muhsi",en:"The Reckoner of All",root:"ح-ص-ي",meaning:"The One who has counted and recorded everything, down to the last atom.",line:"Nothing you've done for Him has been lost in the count."},
 {n:58,slug:"al-mubdi",ar:"ٱلْمُبْدِئُ",tr:"Al-Mubdi'",en:"The Originator",root:"ب-د-أ",meaning:"The One who begins all creation without any prior model.",line:"He started you. He knows how to start you again."},
 {n:59,slug:"al-muid",ar:"ٱلْمُعِيدُ",tr:"Al-Mu'id",en:"The Restorer to Life",root:"ع-و-د",meaning:"The One who brings creation back, repeats it, and returns all things to Him.",line:"What's been lost can be brought back by the One who made it."},
 {n:60,slug:"al-muhyi",ar:"ٱلْمُحْيِي",tr:"Al-Muhyi",en:"The Giver of Life",root:"ح-ي-ي",meaning:"The One who gives life — to bodies, to land, to hearts.",line:"Dead things are where He does His best work."},
 {n:61,slug:"al-mumit",ar:"ٱلْمُمِيتُ",tr:"Al-Mumit",en:"The Bringer of Death",root:"م-و-ت",meaning:"The One who decrees death, by whose command every life ends at its appointed time.",line:"You will not die one second before you're meant to."},
 {n:62,slug:"al-hayy",ar:"ٱلْحَيُّ",tr:"Al-Hayy",en:"The Ever-Living",root:"ح-ي-ي",meaning:"Life that has no beginning, no end, and no dependence on anything.",line:"Everything you lean on will die. Except Him."},
 {n:63,slug:"al-qayyum",ar:"ٱلْقَيُّومُ",tr:"Al-Qayyum",en:"The Sustainer of All",root:"ق-و-م",meaning:"Self-subsisting, and the One by whom everything else subsists.",line:"He's holding up the universe. He can hold up your day."},
 {n:64,slug:"al-wajid",ar:"ٱلْوَاجِدُ",tr:"Al-Wajid",en:"The Finder",root:"و-ج-د",meaning:"The One who finds whatever He wills and lacks nothing.",line:"He's never lost track of you."},
 {n:65,slug:"al-majid-2",ar:"ٱلْمَاجِدُ",tr:"Al-Majid",en:"The Noble",root:"م-ج-د",meaning:"Noble in essence, generous in action, glorious in every way.",line:"Nobility that never needed to be earned."},
 {n:66,slug:"al-wahid",ar:"ٱلْوَاحِدُ",tr:"Al-Wahid",en:"The One",root:"و-ح-د",meaning:"Unique and singular, without partner, equal or likeness.",line:"There's one of Him. That's the whole religion."},
 {n:67,slug:"al-ahad",ar:"ٱلْأَحَدُ",tr:"Al-Ahad",en:"The Unique",root:"أ-ح-د",meaning:"Indivisibly one, with no part, no peer and no second.",line:"Qul huwa Allahu Ahad. Say it. Mean it. Rest in it."},
 {n:68,slug:"as-samad",ar:"ٱلصَّمَدُ",tr:"As-Samad",en:"The Eternal Refuge",root:"ص-م-د",meaning:"The One everything depends on, who depends on nothing; the One you turn to in need.",line:"Everyone needs Him. He needs no one. Go to Him."},
 {n:69,slug:"al-qadir",ar:"ٱلْقَادِرُ",tr:"Al-Qadir",en:"The All-Powerful",root:"ق-د-ر",meaning:"Able to do all things, with no limit and no effort.",line:"'Impossible' is a word for creatures."},
 {n:70,slug:"al-muqtadir",ar:"ٱلْمُقْتَدِرُ",tr:"Al-Muqtadir",en:"The Omnipotent",root:"ق-د-ر",meaning:"Power that is total, that prevails over every other power.",line:"Whatever has power over you answers to Him."},
 {n:71,slug:"al-muqaddim",ar:"ٱلْمُقَدِّمُ",tr:"Al-Muqaddim",en:"The Expediter",root:"ق-د-م",meaning:"The One who brings forward whom He wills, in time, in rank, in blessing.",line:"If it came early, He sent it early."},
 {n:72,slug:"al-muakhkhir",ar:"ٱلْمُؤَخِّرُ",tr:"Al-Mu'akhkhir",en:"The Delayer",root:"أ-خ-ر",meaning:"The One who holds back and delays what He wills, always at the right time.",line:"Late by your clock. On time by His."},
 {n:73,slug:"al-awwal",ar:"ٱلْأَوَّلُ",tr:"Al-Awwal",en:"The First",root:"أ-و-ل",meaning:"Before everything, with nothing before Him.",line:"Before the first thing, He was."},
 {n:74,slug:"al-akhir",ar:"ٱلْآخِرُ",tr:"Al-Akhir",en:"The Last",root:"أ-خ-ر",meaning:"After everything, with nothing after Him.",line:"When everything ends, He won't have."},
 {n:75,slug:"az-zahir",ar:"ٱلظَّاهِرُ",tr:"Az-Zahir",en:"The Manifest",root:"ظ-ه-ر",meaning:"Evident in every sign of creation, above all things.",line:"Look at anything long enough and you'll see His signature."},
 {n:76,slug:"al-batin",ar:"ٱلْبَاطِنُ",tr:"Al-Batin",en:"The Hidden",root:"ب-ط-ن",meaning:"Hidden in His essence, nearer than the jugular vein, known by His signs not His form.",line:"Closer than you can see. That's why you can't see Him."},
 {n:77,slug:"al-wali",ar:"ٱلْوَالِي",tr:"Al-Wali",en:"The Governor",root:"و-ل-ي",meaning:"The One who governs and manages all affairs of creation.",line:"The world is managed. Breathe."},
 {n:78,slug:"al-mutaali",ar:"ٱلْمُتَعَالِي",tr:"Al-Muta'ali",en:"The Self-Exalted",root:"ع-ل-و",meaning:"Exalted far above creation, beyond every limit and every attribute of the created.",line:"Too high for your worries to reach. Not too high to hear them."},
 {n:79,slug:"al-barr",ar:"ٱلْبَرُّ",tr:"Al-Barr",en:"The Source of Goodness",root:"ب-ر-ر",meaning:"Kind and good to His creation, generous in doing good, gentle in every dealing.",line:"Goodness isn't something He does. It's who He is."},
 {n:80,slug:"at-tawwab",ar:"ٱلتَّوَّابُ",tr:"At-Tawwab",en:"The Ever-Returning",root:"ت-و-ب",meaning:"The One who keeps turning back to His servants, and accepts their return every time.",line:"He turns to you first, so that you can turn to Him."},
 {n:81,slug:"al-muntaqim",ar:"ٱلْمُنْتَقِمُ",tr:"Al-Muntaqim",en:"The Avenger",root:"ن-ق-م",meaning:"The One who takes just retribution from the oppressors, after long forbearance.",line:"You don't have to get even. That's His job."},
 {n:82,slug:"al-afuww",ar:"ٱلْعَفُوُّ",tr:"Al-'Afuww",en:"The Pardoner",root:"ع-ف-و",meaning:"The One who erases sins entirely, removing even the record of them.",line:"Forgiveness covers it. Pardon deletes it. Ask for pardon."},
 {n:83,slug:"ar-rauf",ar:"ٱلرَّءُوفُ",tr:"Ar-Ra'uf",en:"The Most Kind",root:"ر-أ-ف",meaning:"Tender and compassionate, with a kindness that is intense and protective.",line:"He is kinder to you than you are to yourself."},
 {n:84,slug:"malik-ul-mulk",ar:"مَالِكُ ٱلْمُلْكِ",tr:"Malik-ul-Mulk",en:"Master of the Kingdom",root:"م-ل-ك",meaning:"The true Owner of all dominion, who gives and takes power as He wills.",line:"Every throne is on loan."},
 {n:85,slug:"dhul-jalali-wal-ikram",ar:"ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ",tr:"Dhul-Jalali wal-Ikram",en:"Lord of Majesty and Generosity",root:"ج-ل-ل · ك-ر-م",meaning:"Majesty that humbles and generosity that honours, held together perfectly.",line:"Feared and loved, in the same breath."},
 {n:86,slug:"al-muqsit",ar:"ٱلْمُقْسِطُ",tr:"Al-Muqsit",en:"The Equitable",root:"ق-س-ط",meaning:"The One who acts with equity, giving everyone their due and restoring rights.",line:"What was taken from you is on record."},
 {n:87,slug:"al-jami",ar:"ٱلْجَامِعُ",tr:"Al-Jami'",en:"The Gatherer",root:"ج-م-ع",meaning:"The One who gathers all things — people, truths, the scattered — together.",line:"He gathers what life scattered."},
 {n:88,slug:"al-ghaniyy",ar:"ٱلْغَنِيُّ",tr:"Al-Ghaniyy",en:"The Self-Sufficient",root:"غ-ن-ي",meaning:"Rich beyond need, independent of all creation, while all creation depends on Him.",line:"He needs nothing from you. He wants you anyway."},
 {n:89,slug:"al-mughni",ar:"ٱلْمُغْنِي",tr:"Al-Mughni",en:"The Enricher",root:"غ-ن-ي",meaning:"The One who makes rich and content, in wealth and in heart.",line:"Enough is a gift, and He gives it."},
 {n:90,slug:"al-mani",ar:"ٱلْمَانِعُ",tr:"Al-Mani'",en:"The Preventer",root:"م-ن-ع",meaning:"The One who withholds and prevents, protecting by what He keeps away.",line:"Some of what you didn't get was protection."},
 {n:91,slug:"ad-darr",ar:"ٱلضَّارُّ",tr:"Ad-Darr",en:"The Distresser",root:"ض-ر-ر",meaning:"The One by whose decree harm and hardship occur, always within His wisdom.",line:"He allows hardship for reasons you'll understand later."},
 {n:92,slug:"an-nafi",ar:"ٱلنَّافِعُ",tr:"An-Nafi'",en:"The Benefactor",root:"ن-ف-ع",meaning:"The Source of all benefit; nothing helps except by His leave.",line:"Everything that ever helped you was Him helping you."},
 {n:93,slug:"an-nur",ar:"ٱلنُّورُ",tr:"An-Nur",en:"The Light",root:"ن-و-ر",meaning:"The Light of the heavens and the earth, by which all things are seen and guided.",line:"Light, by name."},
 {n:94,slug:"al-hadi",ar:"ٱلْهَادِي",tr:"Al-Hadi",en:"The Guide",root:"ه-د-ي",meaning:"The One who guides hearts to Him, and creatures to what is good for them.",line:"You're not lost. You're being led."},
 {n:95,slug:"al-badi",ar:"ٱلْبَدِيعُ",tr:"Al-Badi'",en:"The Incomparable Originator",root:"ب-د-ع",meaning:"The One who creates in wholly original ways, without precedent.",line:"Originality is His. Everything else is a remix."},
 {n:96,slug:"al-baqi",ar:"ٱلْبَاقِي",tr:"Al-Baqi",en:"The Everlasting",root:"ب-ق-ي",meaning:"The One who remains when all else passes away.",line:"This will pass. He will not."},
 {n:97,slug:"al-warith",ar:"ٱلْوَارِثُ",tr:"Al-Warith",en:"The Inheritor",root:"و-ر-ث",meaning:"The One to whom everything returns when all owners are gone.",line:"Everything ends up with Him. Including you."},
 {n:98,slug:"ar-rashid",ar:"ٱلرَّشِيدُ",tr:"Ar-Rashid",en:"The Guide to the Right Path",root:"ر-ش-د",meaning:"The One whose every plan is right, and who directs to what is right.",line:"His plan for you has no errors in it."},
 {n:99,slug:"as-sabur",ar:"ٱلصَّبُورُ",tr:"As-Sabur",en:"The Infinitely Patient",root:"ص-ب-ر",meaning:"Patience without limit; He does not hasten punishment, and He waits for you to return.",line:"He has never once rushed you."},
];

export const bySlug = (slug: string) => NAMES.find(n => n.slug === slug);

// One name a week, starting Monday 5 Jan 2026, cycling through all 99.
export function weeklyIndex(date = new Date()): number {
  const start = Date.UTC(2026, 0, 5);
  const weeks = Math.floor((date.getTime() - start) / (7 * 24 * 3600 * 1000));
  return ((weeks % 99) + 99) % 99;
}
export const weeklyName = (date = new Date()) => NAMES[weeklyIndex(date)];

// Arabic-Indic numerals
export const arNum = (n: number) => String(n).replace(/\d/g, d => "٠١٢٣٤٥٦٧٨٩"[+d]);
